{
  "hash": "44972c945512dbd1b8608627e8d04941",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Effect sizes\"\nsubtitle: \"Understanding, choosing and computing the currency of meta-analysis\"\n---\n\n\n\n## Learning objectives {.objectives}\n\nBy the end of this session, you will be able to:\n\n1.  Explain what an **effect size** is and why each one comes with a **sampling variance**.\n2.  **Choose** the right metric for your data: mean difference, Hedges' *g*, log response ratio, log odds ratio, Fisher's *z*.\n3.  **Compute** them by hand and with `metafor::escalc()`.\n4.  Recognise the **traps**: small samples, near-zero means, missing SDs, unsafe conversions.\n\n::: notes\n60 min: ~35 min lecture, 2 exercises (~15 min), quiz (~3 min). Everything uses the running example: intercropping vs monoculture.\n:::\n\n# What is an effect size? {.section-divider background-image=\"../../theme/img/bg-keymessages.jpg\"}\n\n## Studies do not speak the same language\n\n::: {.columns}\n::: {.column width=\"50%\"}\nThe 888 intercropping comparisons of our running example report biodiversity as:\n\n-   **abundance** or **species richness**,\n-   in individuals per trap, per plant, per m², per hour...\n-   with **SD**, **SE**, **95% CI** or **median + IQR** as the measure of spread.\n\n::: {.fragment .box .blue}\n[An effect size]{.box-title}\nputs all studies on **one common scale**: the **direction** and **magnitude** of the difference between intervention and comparator — plus its **uncertainty**.\n:::\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-reported-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n::: {.source}\nSource: @jones2021; the authors converted everything to SD before sharing the data.\n:::\n\n## Why not just use p-values?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-pvalue-1.png){width=100%}\n:::\n:::\n\n\n::: {.columns}\n::: {.column width=\"50%\"}\n::: {.box .warn}\nA p-value mixes **effect size** and **sample size**: a tiny effect can be \"highly significant\", a large one \"not significant\".\n:::\n:::\n::: {.column width=\"48%\"}\n::: {.fragment .box .green}\nMeta-analysis combines **effect sizes and their uncertainty**, not p-values [@nakagawa2007].\n:::\n:::\n:::\n\n## Every study sees the truth through noise\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-sampling-1.png){width=100%}\n:::\n:::\n\n\n$$\\hat\\theta_k = \\theta_k + \\varepsilon_k \\qquad \\text{observed} = \\text{true} + \\text{sampling error}, \\quad \\text{Var}(\\varepsilon_k) = v_k$$\n\n::: {.fragment .box .blue style=\"width:80%;\"}\nEach effect size comes with its **sampling variance** $v_k$. In the meta-analysis this afternoon, each study is **weighted** by the inverse of its variance, $w_k = 1/v_k$: precise studies count more. (In a random-effects model, the weight also includes the real variation between studies, $\\tau^2$: $w_k = 1/(v_k + \\tau^2)$.)\n:::\n\n::: notes\n~3 min. We observe theta-hat and can estimate its variance v from the study's SD and n. We never observe the true theta. The sampling variance shrinks with n: that is what the three panels show.\n:::\n\n# Which metric for which data? {.section-divider background-image=\"../../theme/img/bg-keymessages.jpg\"}\n\n## A decision tree\n\n```{=html}\n<div style=\"display:grid; grid-template-columns: 1fr 1fr 1fr; gap:18px; font-size:0.95em; margin-top:10px;\">\n  <div class=\"box blue\" style=\"margin:0;\"><b>Continuous outcome, two groups</b><br><span class=\"muted\">means, SD, n</span>\n    <ul style=\"margin-top:8px;\">\n      <li>Same unit everywhere &rarr; <b>Mean difference (MD)</b></li>\n      <li>Different scales, additive effect &rarr; <b>standardised mean difference</b> (Hedges' <i>g</i>)</li>\n      <li>Positive values, proportional effect &rarr; <b>log response ratio (lnRR)</b></li>\n    </ul></div>\n  <div class=\"box green\" style=\"margin:0;\"><b>Binary outcome, two groups</b><br><span class=\"muted\">counts in a 2&times;2 table</span>\n    <ul style=\"margin-top:8px;\">\n      <li>Presence/absence, survival, infestation &rarr; <b>log odds ratio</b> (or log risk ratio)</li>\n    </ul></div>\n  <div class=\"box\" style=\"margin:0;\"><b>Relationship between two continuous variables</b><br><span class=\"muted\">correlation r, n</span>\n    <ul style=\"margin-top:8px;\">\n      <li>e.g. yield vs landscape complexity &rarr; <b>Fisher's <i>z</i></b></li>\n    </ul></div>\n</div>\n```\n\n::: {.columns style=\"margin-top:18px;\"}\n::: {.column width=\"50%\"}\n::: {.box .blue}\n**Proportional** (→ lnRR): \"−30% aphids\", same meaning with 10 or 1,000 aphids. Abundance, biomass, yield: a true zero, effects multiply.\\\n**Additive** (→ *g*): \"+5 units\". Scores, indices, variables with an arbitrary zero.\n:::\n:::\n::: {.column width=\"48%\"}\n::: {.fragment .box .warn}\nIn ecology and agronomy, **lnRR** and **Hedges' *g*** (a standardised mean difference, SMD) dominate. Our running example → **lnRR**. Fix the metric **in the protocol**, before seeing the results.\n:::\n:::\n:::\n\n::: {.fragment .small .muted}\nShow of hands: *which metric for your own data?*\n:::\n\n::: notes\n~4 min. The choice follows the data AND the question: an additive vs a proportional effect. Changing metric after looking at the results is a form of p-hacking.\n:::\n\n## Our worked example\n\n::: {.columns}\n::: {.column width=\"46%\"}\nAphids on fennel, **intercropped with cotton** vs **fennel monoculture** [@fernandes2013], one comparison of our dataset:\n\n| | Intercropping (T) | Monoculture (C) |\n|---|---|---|\n| Mean | 8.37 | 23.98 |\n| SD | 2.85 | 5.46 |\n| n | 4 | 4 |\n:::\n\n::: {.column width=\"52%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-example-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n::: {.box .blue}\nConvention for the whole week: **T (intervention) in the numerator / first**, C (comparator) second. A negative effect = fewer pests with intercropping.\n:::\n\n## The log response ratio (lnRR)\n\n::: {.columns}\n::: {.column width=\"52%\"}\n$$\\ln RR = \\ln\\left(\\frac{\\bar X_T}{\\bar X_C}\\right)$$\n\n$$v_{\\ln RR} = \\frac{SD_T^2}{n_T \\bar X_T^2} + \\frac{SD_C^2}{n_C \\bar X_C^2}$$\n\n<span class=\"small muted\">[@hedges1999]</span>\n\n**Back to percent** for reporting:\n\n$$\\text{change} = 100 \\times \\left(e^{\\ln RR} - 1\\right)\\%$$\n:::\n\n::: {.column width=\"46%\"}\n::: {.box .blue}\n[Why the log?]{.box-title}\nThe ratio is **asymmetric** (halving = 0.5, doubling = 2); its log is **symmetric** (−0.69, +0.69) and closer to normal.\n:::\n\n::: {.box .green}\n[Why ecologists like it]{.box-title}\n**Unit-free** and **proportional**: \"intercropping reduces aphids by 65%\" speaks to agronomists — and its value does not depend on the SD (only its variance does).\n:::\n:::\n:::\n\n## Exercise 1 · By hand (pairs, 8 min) {.question}\n\n::: question-card\n[Calculator ready]{.q-kicker}\n\n[With the aphid example (T: 8.37 ± 2.85, n = 4; C: 23.98 ± 5.46, n = 4), compute **lnRR**, its **variance**, and the **% change**.]{.q-text}\n:::\n\n::: {.fragment .box .green style=\"width:80%;\"}\nlnRR = ln(8.37 / 23.98) = **-1.053**\\\n*v* = 2.85² / (4 × 8.37²) + 5.46² / (4 × 23.98²) = **0.0419** (SE = 0.205)\\\nChange = 100 × (e^-1.053^ − 1) = **-65%**\\\n:::\n\n::: notes\nGive 6–8 min, walk around; expect e^x to be the stumbling block. Then reveal. Keep the answer (-1.053) in mind: the very next slide asks participants to predict what R returns.\n:::\n\n## Now let R do it (live coding, 5 min)\n\n::: {.question-card style=\"width:100%; padding:0.4em 0.9em;\"}\n[Predict first]{.q-kicker} [What value of yi should R return for our aphid example?]{.q-text style=\"font-size:0.9em;\"}\n:::\n\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nlibrary(metafor)\n# ic <- read.csv(\"intercropping_biodiversity.csv\")      # running example\n\ndat <- escalc(measure = \"ROM\",                           # lnRR (\"ratio of means\")\n              m1i = b_mean_t, sd1i = b_sd_t, n1i = b_n_t,  # T = intercropping\n              m2i = b_mean_c, sd2i = b_sd_c, n2i = b_n_c,  # C = monoculture\n              data = ic)\n# other metrics: measure = \"SMD\" (Hedges' g), \"OR\", \"ZCOR\"\n\ndat[dat$es_id == 2011, c(\"es_id\", \"yi\", \"vi\")]          # our worked example\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    es_id      yi     vi \n137  2011 -1.0526 0.0419 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(NA_yi = sum(is.na(dat$yi)), vi_zero = sum(dat$vi == 0, na.rm = TRUE))  # what to deal with\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  NA_yi vi_zero \n    156      46 \n```\n\n\n:::\n:::\n\n\n::: {.fragment .small}\n-   `yi` = effect size, `vi` = sampling variance: **the input of every meta-analysis** (`rma()`, this afternoon).\n-   Zero mean → `NA`; zero SD → `vi = 0` (\"infinite\" precision!): **count both** before `rma()`.\n:::\n\n::: notes\nAsk for the prediction (-1.053 from Exercise 1) before running. For SMD, escalc uses the exact J (gamma function): g = -3.113, vs -3.117 with the approximate J by hand.\n:::\n\n## Hedges' *g*, step by step\n\n::: {.columns}\n::: {.column width=\"44%\"}\n**Idea**: express the difference in **standard-deviation units**.\n\n$$d = \\frac{\\bar X_T - \\bar X_C}{SD_{pooled}}$$\n\nUseful when studies use **different scales** and the effect is additive.\n\n::: {.box .warn}\nSmall samples **inflate** *d* → multiply by a correction *J* < 1: that is **Hedges' *g*** [@hedges1981].\n:::\n:::\n\n::: {.column width=\"54%\"}\nWith our aphids:\n\n::: {.fragment}\n**1.** Difference: 8.37 − 23.98 = **-15.61** aphids\n:::\n\n::: {.fragment}\n**2.** Pooled SD (equal *n*: average the variances): √((2.85² + 5.46²) / 2) = **4.36**\n:::\n\n::: {.fragment}\n**3.** *d* = -15.61 / 4.36 = **-3.58** standard deviations\n:::\n\n::: {.fragment}\n**4.** With 4 + 4 plants, *J* = 0.87 → ***g*** = **-3.12**\n:::\n\n::: {.fragment .box .green}\n`escalc(measure = \"SMD\")` does all of this — and the variance. You never compute *g* by hand in practice.\n:::\n:::\n:::\n\n::: notes\n~4 min, demonstrated by the teacher after Exercise 1 (not asked to participants). All formulas (pooled SD, J, variance of g) are in the formula sheet at the end.\n:::\n\n# The traps {.section-divider background-image=\"../../theme/img/bg-keymessages.jpg\"}\n\n## Trap 1 · Means close to zero {.question}\n\n::: question-card\n[Your call]{.q-kicker}\n\n[156 comparisons in our data have a **zero mean**. What do you do with them for a lnRR?]{.q-text}\n:::\n\n::: {.columns}\n::: {.column width=\"48%\"}\n::: {.fragment}\n**Exact zeros**: no lnRR (and most also have SD = 0, so no *g*). Report them; test the conclusion **with and without**.\n:::\n\n::: {.fragment}\n**Near zero**: lnRR is biased. Geary's rule: each mean ≥ **3 SE** from zero → **28%** of our usable comparisons fail it.\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.fragment .box .blue}\n[What to do]{.box-title}\n\n-   Near zero or small *n*: **bias-corrected lnRR** [@lajeunesse2015] — formula and R code on the handout.\n-   **Never** add an arbitrary constant (+1) without testing its influence.\n:::\n:::\n:::\n\n::: notes\n~3 min. Ask first, collect 2–3 answers, then reveal. Note that mean*sqrt(n)/SD = mean/SE. Lajeunesse (2015) gives a small-sample version of Geary's test (handout). The bias of lnRR grows when mean/SE is small, whether because n is small or the mean is near zero. Correction formula in the formula sheet.\n:::\n\n## Trap 2 · Missing or disguised SDs\n\n::: {.columns}\n::: {.column width=\"55%\"}\n::: {.box .blue}\n[The common case: a standard error]{.box-title}\n**SD = SE × √n**\\\n553 of our 888 comparisons were reported with a SE.\n:::\n\n::: {.small .muted}\nAlso possible: from a 95% CI, or from a median and IQR [@wan2014] — see the formula sheet.\n:::\n:::\n\n::: {.column width=\"43%\"}\n::: {.fragment .box .warn}\n**215** comparisons (**24%**) have **no usable SD**.\\\nNever set it to 0 or drop silently. Robust fix for lnRR: compute the sampling variance from the **average squared coefficient of variation** (CV = SD/mean, weighted by *n*) of the other studies [@nakagawa2023]. Not possible for zero means.\n:::\n:::\n:::\n\n::: {.fragment .small}\nTraps 1 and 2 together: **224** of 888 comparisons (25%) are unusable as such for lnRR. This afternoon we set them aside — and say so.\n:::\n\n::: notes\n~2 min. Link with Joseph's session on quantitative extraction (metaDigitise): values read from figures are often SEs. Always record which spread measure was reported — a codebook column.\n:::\n\n## Trap 3 · lnRR and *g*: same direction, different magnitudes\n\n::: {.columns}\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-g-lnrr-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"43%\"}\nThe 664 usable comparisons, computed both ways:\n\n-   Same **direction** always (both follow $\\bar X_T - \\bar X_C$)\n-   Similar **ranking** (Spearman ρ = 0.84)\n-   But very different **magnitudes**: *g* explodes when the SD is tiny\n\n::: {.fragment .box .warn}\n*g* depends on the SD (trap size, plot size, subsamples); lnRR does not. **Never mix both** in one analysis, and do not convert lnRR ↔ *g*.\n:::\n:::\n:::\n\n## Other kinds of data, in one slide\n\n::: {.columns}\n::: {.column width=\"50%\"}\n::: {.box .green}\n[Yes/no outcomes]{.box-title}\nPlants infested or not, seedlings alive or dead → a 2×2 table of counts → **log odds ratio** (or log risk ratio, the log of the ratio of proportions).\\\n`escalc(\"OR\", ai=, bi=, ci=, di=)`\n:::\n:::\n\n::: {.column width=\"48%\"}\n::: {.box}\n[Correlations]{.box-title}\ne.g. habitat cover vs pest control → **Fisher's *z***.\\\nPool ***z***, not *r*, then back-transform.\\\n`escalc(\"ZCOR\", ri=, ni=)`\n:::\n:::\n:::\n\n::: {.box .warn}\n[Conversions between metrics]{.box-title}\nPossible (log OR → *d*, *r* → *d*), but only for a **minority** of studies: flag them and run a **sensitivity analysis** without them. **Never lnRR ↔ *g***. Formulas in the formula sheet [@borenstein2021, chap. 7].\n:::\n\n::: notes\n~3 min. No formulas here on purpose: the formula sheet at the end has them.\n:::\n\n## Quick quiz {.question}\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**1.** Earthworm biomass (g/m²) under conservation vs conventional tillage, studies in many different units. Metric?\n\n::: {.fragment .box .green}\n**lnRR** — positive, proportional, unit-free.\n:::\n\n**2.** lnRR = −0.36. Change in %?\n\n::: {.fragment .box .green}\n100 × (e^−0.36^ − 1) = **−30%**.\n:::\n:::\n\n::: {.column width=\"48%\"}\n**3.** Proportion of fields where a weed is present, with vs without cover crop. Metric?\n\n::: {.fragment .box .green}\n**log odds ratio** (or log risk ratio).\n:::\n\n**4.** Why use *g* rather than *d*?\n\n::: {.fragment .box .green}\n*d* **overestimates |effect|** in small samples; *g* corrects it.\n:::\n:::\n:::\n\n## Key messages {.key-messages background-image=\"../../theme/img/bg-keymessages.jpg\"}\n\n1.  **Effect size + sampling variance** = the unit of every meta-analysis; the variance becomes the **weight**.\n2.  The **data and the question** choose the metric: MD, *g*, lnRR, log OR, *z*. Fix it in the protocol.\n3.  lnRR: check **Geary**, correct small-sample **bias**, handle **zeros** and **missing SDs** explicitly.\n4.  Never mix **non-convertible** metrics (lnRR ↔ *g*); flag and test any conversion.\n\n## Going further\n\n**All formulas** (with the exact *J*, bias-corrected lnRR and its variance, conversions and their variances): see the **A4 formula sheet** handout.\n\n\n-   **Variability as an outcome**: lnCVR, the log ratio of coefficients of variation [@nakagawa2015].\n-   **Paired / before–after designs** (SMCC, ROMC in `escalc`) need the correlation between measurements.\n-   **Several treatments vs one control** create **dependent** effect sizes → multilevel models, this afternoon.\n\n## In the online notebook {.dense}\n\nEach point of this session developed further, with the same data, more pitfalls and exercises with solutions:\n\n-   [Effect sizes](https://literaturesynthesis.github.io/notebook/chapters/effect-sizes.html)\n-   [Formula sheet (appendix)](https://literaturesynthesis.github.io/notebook/chapters/formulas.html)\n-   [From research question to estimand](https://literaturesynthesis.github.io/notebook/chapters/question-estimand.html)\n-   [Dependence: map it before you model it](https://literaturesynthesis.github.io/notebook/chapters/dependence.html)\n\n::: {.box .blue}\n**literaturesynthesis.github.io/notebook**\n:::\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}