{
  "hash": "267762571b00814e4d2db094125d77e5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Explaining heterogeneity in R\"\nsubtitle: \"Practical · Wednesday 16:33–16:55 · FRB-CESAB training course\"\nauthor: \"Damien Beillouin\"\nformat:\n  html:\n    theme: [cosmo, ../../theme/cesab-doc.scss]\n    toc: true\n    toc-location: left\n    toc-title: \"Practical\"\n    number-sections: true\n    embed-resources: true\n    html-math-method: mathml\n    code-copy: true\n    fig-width: 8\n    fig-height: 4.5\n    fig-dpi: 150\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n## By the end of this practical, you will be able to\n\n1.  Fit and read a **meta-regression** (omnibus test, coefficients, pseudo-R²).\n2.  Separate the **within-study** from the **between-study** part of a moderator effect.\n3.  Check coefficients of variation and **impute missing SDs** transparently.\n:::\n\n| Time | What | Section |\n|------|------|---------|\n| 16:33 | Meta-regression: pests vs natural enemies (1 blank) | [1](#setup) · [2](#metareg) |\n| 16:40 | Within- vs between-study (1 blank) · *optional:* validity | [3](#within) |\n| 16:47 | Missing SDs (code given: run and interpret) | [4](#missing) |\n\nWork **in pairs**. Only two blanks (`___`) to fill: the rest of the script is given, and the work is to **read and discuss the outputs**. The questions are in the script (`# Q:`).\n| 16:55 | Debrief (until 17:00) | [5](#key) |\n\n# Setup {#setup}\n\nOpen `meta_analysis_course.Rproj` (the course kit), then `td_advanced.R` (exercises with blanks `___`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(metafor)\nlibrary(ggplot2)\n\n# In the participant pack: data_file <- \"intercropping_biodiversity.csv\"\nic <- read.csv(data_file)\n\ndat <- ic |>\n  filter(functional_group %in% c(\"Pests\", \"Natural enemies\"), !sd_missing, !zero_mean) |>\n  escalc(measure = \"ROM\", m1i = b_mean_t, sd1i = b_sd_t, n1i = b_n_t,\n         m2i = b_mean_c, sd2i = b_sd_c, n2i = b_n_c, data = _)\n\npct <- function(x) round(100 * (exp(x) - 1), 1)\nfit <- function(d, mods = ~ 1)          # the multilevel model of this afternoon\n  rma.mv(yi, vi, mods = mods, random = ~ 1 | study_id / es_id,\n         data = d, test = \"t\", dfs = \"contain\")\n\ntable(dat$functional_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNatural enemies           Pests \n            195             382 \n```\n\n\n:::\n:::\n\n\n# Meta-regression {#metareg}\n\n**Predict first:** will intercropping have the same effect on pests and on their natural enemies?\n\n**Exercise 1.** Add `functional_group` as a moderator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- fit(dat)                          # no moderator\nm1 <- fit(dat, mods = ~ ___)            # with moderator\nm1                                      # find: Test of Moderators (F, p)\nrobust(m1, cluster = study_id, clubSandwich = TRUE)   # few studies: check with CR2\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- fit(dat)\nm1 <- fit(dat, mods = ~ functional_group)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 577; method: REML)\n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed          factor \nsigma^2.1  0.1211  0.3480     34     no        study_id \nsigma^2.2  0.1720  0.4147    577     no  study_id/es_id \n\nTest for Residual Heterogeneity:\nQE(df = 575) = 160501.6025, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 575) = 52.2656, p-val < .0001\n\nModel Results:\n\n                       estimate      se     tval   df    pval    ci.lb    ci.ub \nintrcpt                  0.1269  0.0768   1.6531   32  0.1081  -0.0295   0.2834 \nfunctional_groupPests   -0.4348  0.0601  -7.2295  575  <.0001  -0.5530  -0.3167 \n                           \nintrcpt                    \nfunctional_groupPests  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nm1r <- robust(m1, cluster = study_id, clubSandwich = TRUE)\nm1r\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 577; method: REML)\n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed          factor \nsigma^2.1  0.1211  0.3480     34     no        study_id \nsigma^2.2  0.1720  0.4147    577     no  study_id/es_id \n\nTest for Residual Heterogeneity:\nQE(df = 575) = 160501.6025, p-val < .0001\n\nNumber of estimates:   577\nNumber of clusters:    34\nEstimates per cluster: 1-80 (mean: 16.97, median: 11.5)\n\nTest of Moderators (coefficient 2):¹\nF(df1 = 1, df2 = 10.04) = 20.3527, p-val = 0.0011\n\nModel Results:\n\n                       estimate      se¹     tval¹     df¹    pval¹    ci.lb¹ \nintrcpt                  0.1269  0.0893    1.4218   25.19   0.1674   -0.0569  \nfunctional_groupPests   -0.4348  0.0964   -4.5114   10.04   0.0011   -0.6495  \n                         ci.ub¹     \nintrcpt                 0.3108      \nfunctional_groupPests  -0.2202   ** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n1) results based on cluster-robust inference (var-cov estimator: CR2,\n   approx t/F-tests and confidence intervals, df: Satterthwaite approx)\n```\n\n\n:::\n:::\n\n\n-   **Test of Moderators**: *F* is large, *p* < 0.001 → the effect differs between groups.\n-   With **cluster-robust (CR2)** tests the denominator df drop to about **10** (only a few studies carry the contrast), but *p* stays ≈ 0.001: the difference survives.\n-   `intrcpt` = natural enemies (reference level); `functional_groupPests` = **difference** pests − natural enemies (lnRR scale).\n:::\n\n**Exercise 2** (code given — run and read). One estimate per group (intercept removed with `0 +`) and the share of heterogeneity explained. How large is the pseudo-R²? At which level does the moderator explain something?\n\n::: {.callout-note collapse=\"true\" title=\"Code and answer\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm1b <- fit(dat, mods = ~ 0 + functional_group)\npct(coef(m1b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfunctional_groupNatural enemies           functional_groupPests \n                           13.5                           -26.5 \n```\n\n\n:::\n\n```{.r .cell-code}\nR2 <- 1 - sum(m1$sigma2) / sum(m0$sigma2)\nround(100 * R2, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.8\n```\n\n\n:::\n\n```{.r .cell-code}\nround(100 * (1 - m1$sigma2 / m0$sigma2), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1.7 14.7\n```\n\n\n:::\n:::\n\n\nPests decrease, natural enemies tend to increase — consistent with the *enemies hypothesis*. But the moderator explains only about **10%** of the heterogeneity overall, and almost all of it **within studies** (~15%) rather than between studies (~2%). Pseudo-R² is rough (it can even be negative) — both models must be fitted on **the same rows**, as here.\n:::\n\n# Within-study check and study quality {#within}\n\n**Exercise 3.** Split the moderator into a **within-study** part (does a study that measured both groups see a difference?) and a **between-study** part (do studies of pests differ from studies of enemies?). Only a few studies measured both groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat |>\n  mutate(pest = as.numeric(functional_group == \"Pests\")) |>\n  group_by(study_id) |>\n  mutate(pest_m = mean(pest),          # share of pest rows in the study (between)\n         pest_w = pest - ___) |>       # deviation from the study mean (within)\n  ungroup()\nsum(tapply(dat$pest, dat$study_id, function(x) length(unique(x))) == 2)  # studies with both\nm_wb <- fit(dat, mods = ~ pest_w + pest_m)\npct(coef(m_wb)[-1])\nm_wb\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat |>\n  mutate(pest = as.numeric(functional_group == \"Pests\")) |>\n  group_by(study_id) |>\n  mutate(pest_m = mean(pest), pest_w = pest - pest_m) |>\n  ungroup()\nsum(tapply(dat$pest, dat$study_id, function(x) length(unique(x))) == 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n\n```{.r .cell-code}\nm_wb <- fit(dat, mods = ~ pest_w + pest_m)\npct(coef(m_wb)[-1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npest_w pest_m \n -36.1  -27.6 \n```\n\n\n:::\n\n```{.r .cell-code}\nm_wb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 577; method: REML)\n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed          factor \nsigma^2.1  0.1226  0.3501     34     no        study_id \nsigma^2.2  0.1721  0.4148    577     no  study_id/es_id \n\nTest for Residual Heterogeneity:\nQE(df = 574) = 110568.4394, p-val < .0001\n\nTest of Moderators (coefficients 2:3):\nF(df1 = 2, df2 = 31) = 26.3119, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb    ci.ub      \nintrcpt    0.0574  0.1341   0.4284   31  0.6714  -0.2161   0.3310      \npest_w    -0.4481  0.0637  -7.0398  574  <.0001  -0.5731  -0.3231  *** \npest_m    -0.3233  0.1863  -1.7356   31  0.0926  -0.7032   0.0566    . \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n-   **Within** studies (same field, year, crop): pests about **−36%** relative to natural enemies, clearly different from 0.\n-   **Between** studies: about **−28%**, and uncertain (*p* ≈ 0.09).\n-   Same direction and similar size: the difference is not just an artefact of *which* studies measured *which* group. The within-study estimate is the one that controls for study context — it is the stronger evidence.\n:::\n\n*(optional)* **Exercise 4.** For natural enemies only, is study quality (`validity_biodiv`) a moderator? How many comparisons could not be appraised?\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nne <- filter(dat, functional_group == \"Natural enemies\")\nsum(is.na(ne$validity_biodiv))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n\n```{.r .cell-code}\nm_v <- fit(ne, mods = ~ 0 + factor(validity_biodiv))\npct(coef(m_v))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfactor(validity_biodiv)0 factor(validity_biodiv)1 \n                    -7.0                     26.6 \n```\n\n\n:::\n\n```{.r .cell-code}\nfit(ne, mods = ~ factor(validity_biodiv))$pval[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01407015\n```\n\n\n:::\n:::\n\n\nComparisons meeting all validity criteria show a clear increase of natural enemies; the others show none. But the \"not valid\" level rests on only **6 studies** (93 rows) and the \"valid\" one on 12 studies: a between-study association with few clusters. Poor designs may mask a real benefit — or valid studies differ in other ways (crop, region, taxa). And 1 comparison in 5 could not be appraised at all.\n:::\n\n# Missing SDs {#missing}\n\nBack to **pests**, this time keeping the comparisons without a usable SD (but with non-zero means).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npz <- ic |> filter(functional_group == \"Pests\", !zero_mean)\nc(total = nrow(pz), sd_missing = sum(pz$sd_missing))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     total sd_missing \n       440         58 \n```\n\n\n:::\n:::\n\n\n**Exercise 5. Check the CVs first** (code given — run and read). The coefficient of variation (SD / mean) of each **study** with SDs. Which studies look implausible?\n\n::: {.callout-note collapse=\"true\" title=\"Code and answer\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ncvs <- pz |>\n  filter(!sd_missing) |>\n  mutate(cv_t = b_sd_t / b_mean_t, cv_c = b_sd_c / b_mean_c)\ncvs |>\n  group_by(study_id) |>\n  summarise(cv = mean((cv_t + cv_c) / 2), n = mean(b_n_t)) |>\n  arrange(desc(cv)) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  study_id    cv      n\n     <int> <dbl>  <dbl>\n1      729  9.49 1200  \n2      722  3.82   53.7\n3     1323  2.43   20  \n4      638  1.80   15  \n5      635  1.76   60  \n```\n\n\n:::\n:::\n\n\nTwo studies (722 and 729) have a mean CV above 3 — study 729 with *n* = 1,200 per group. In the database, these SDs were **rebuilt as SE × √n** with *n* = the number of subsamples, not of independent plots (pseudo-replication): the \"SD\" is inflated and so is *n*. **Go back to the paper, and recompute from it — never just patch the number.** Here we set these two studies aside, both from the CV pool and from the analysis.\n:::\n\n**Exercise 6. Impute and compare** (code given — run it and read the output).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuspect <- c(722, 729)                  # studies flagged in Exercise 5\n# typical CV = mean CV weighted by n, per group, then squared\n# (Nakagawa et al. 2023; what metafor does with vtype = \"AV\")\nweighted.mean(cvs$cv_t, cvs$b_n_t)^2          # without the screen: absurd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28.09928\n```\n\n\n:::\n\n```{.r .cell-code}\nok   <- filter(cvs, !study_id %in% suspect)\ncv2t <- weighted.mean(ok$cv_t, ok$b_n_t)^2\ncv2c <- weighted.mean(ok$cv_c, ok$b_n_c)^2\nc(cv2t, cv2c)                           # with the screen: plausible\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2149715 0.2090545\n```\n\n\n:::\n\n```{.r .cell-code}\npz <- pz |>\n  mutate(yi = log(b_mean_t / b_mean_c),\n         vi = ifelse(sd_missing,\n                     cv2t / b_n_t + cv2c / b_n_c,          # imputed: typical CV, squared\n                     b_sd_t^2 / (b_n_t * b_mean_t^2) +     # observed SDs\n                       b_sd_c^2 / (b_n_c * b_mean_c^2))) |>\n  filter(!study_id %in% suspect)\ntable(pz$study_id[pz$sd_missing])       # where do the imputed rows come from?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n524 525 742 763 \n  2  45   4   2 \n```\n\n\n:::\n\n```{.r .cell-code}\nm_cc  <- fit(filter(pz, !sd_missing))\nm_imp <- fit(pz)\nrbind(complete_cases = pct(c(m_cc$b,  m_cc$ci.lb,  m_cc$ci.ub)),\n      with_imputed   = pct(c(m_imp$b, m_imp$ci.lb, m_imp$ci.ub)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                [,1]  [,2]  [,3]\ncomplete_cases -28.0 -42.1 -10.5\nwith_imputed   -30.2 -45.3 -10.9\n```\n\n\n:::\n:::\n\n\n::: {.callout-caution icon=\"false\"}\n## Interpret\nDoes the conclusion change? What would you write in the methods and results sections?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Answer\"}\nNearly identical estimates (about −28% vs −30%): the conclusion is robust to the missing SDs. But look where the imputed rows come from: **45 of 53 from a single study (525)**. The first step is to go back to that paper. Without the CV screen, the squared typical CV is about 30 instead of about 0.2, and imputation would have given these rows almost no weight. Report the number of comparisons with imputed variances, the method [@nakagawa2023], the CV screening (and the studies set aside), and both results.\n:::\n\n# Debrief {#key}\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n1.  Meta-regression tests whether a moderator **explains** heterogeneity: report the omnibus test, coefficients **and** residual heterogeneity (pseudo-R²).\n2.  Between-study moderator effects are **associations**; within-study contrasts are stronger.\n3.  Missing SDs: **check CVs by study**, recompute from the paper when you can, impute transparently, compare with complete cases.\n4.  Tomorrow (group projects): the biodiversity–yield pairs (`biodiversity_yield_pairs.csv`) are a good playground for a multivariate question.\n:::\n\n## Going further in the online notebook {.unnumbered}\n\n-   [Moderators, missing data and networks](https://literaturesynthesis.github.io/notebook/chapters/heterogeneity-moderators.html)\n-   [Certainty of evidence and what can be inferred](https://literaturesynthesis.github.io/notebook/chapters/certainty.html)\n-   [Your turn: soil carbon under agroforestry (end-to-end exercise)](https://literaturesynthesis.github.io/notebook/chapters/your-turn.html)\n-   [Before you submit: a checklist](https://literaturesynthesis.github.io/notebook/chapters/checklist.html)\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}