"""Build theme/cesab.scss from cesab.src.scss.
Inlines (as data URIs) the default slide background and the Poppins fonts, so
that each deck is ONE self-contained HTML file that also works offline.
Run from the project root:  python3 theme/build_theme.py"""
import base64, pathlib
here = pathlib.Path(__file__).parent
b64 = lambda p: base64.b64encode((here / p).read_bytes()).decode()
fonts = [("Regular", 400, "normal"), ("Italic", 400, "italic"), ("Medium", 500, "normal"),
         ("SemiBold", 600, "normal"), ("Bold", 700, "normal")]
ff = "\n".join(
    f'@font-face {{ font-family: "Poppins"; font-weight: {w}; font-style: {s}; '
    f'src: url("data:font/woff2;base64,{b64(f"fonts/Poppins-{n}.woff2")}") format("woff2"); }}'
    for n, w, s in fonts)
for name in ["cesab", "cesab-doc"]:          # slides theme, document theme
    src = (here / f"{name}.src.scss").read_text()
    out = (src.replace("@@BG_CONTENT@@", "data:image/jpeg;base64," + b64("img/bg-content.jpg"))
              .replace("@@FONTS@@", ff))
    (here / f"{name}.scss").write_text(
        f"// GENERATED by build_theme.py from {name}.src.scss - edit the source, not this file\n" + out)
    print(f"theme/{name}.scss written")
