{
  "hash": "7662036a87b848b92471f9bf32ac7e8f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pooling effect sizes in R\"\nsubtitle: \"Practical · Wednesday 14:25–15:00 · FRB-CESAB training course\"\nauthor: \"Damien Beillouin\"\nformat:\n  html:\n    theme: [cosmo, ../../theme/cesab-doc.scss]\n    toc: true\n    toc-location: left\n    toc-title: \"Practical\"\n    number-sections: true\n    embed-resources: true\n    html-math-method: mathml\n    code-copy: true\n    fig-width: 9\n    fig-height: 4.5\n    fig-dpi: 150\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n## By the end of this practical, you will be able to\n\n1.  Fit **common-effect**, **random-effects** and **multilevel** models with `metafor`, and compare their **weights** and **confidence intervals**.\n2.  Report **τ², I²** and the **prediction interval**.\n3.  Add a **robust** (cluster-robust) safety net.\n4.  Draw an **orchard plot**.\n:::\n\n| Time | What | Section |\n|------|------|---------|\n| 14:22 | Load and compute effect sizes | [1](#setup) |\n| 14:24 | Common vs random effects | [2](#models) |\n| 14:30 | Heterogeneity and prediction interval | [3](#hetero) |\n| 14:38 | Multilevel model + robust | [4](#multilevel) |\n| 14:46 | Orchard plot, then your turn: *natural enemies* | [5](#plot) · [6](#turn) |\n| 14:55 | **Debrief** with the whole group | [7](#key) |\n\nSections marked *(optional)* are for those who are ahead: skip them if you are short of time.\n\n# Setup {#setup}\n\nOpen `meta_analysis_course.Rproj` (the course kit), then `td_models.R` (it contains every exercise with blanks `___`). Same data and same effect sizes as this morning: **pest abundance, intercropping vs monoculture**. As announced this morning, comparisons with a zero mean or no usable SD are **set aside** (`!sd_missing, !zero_mean`) — in a real review, report how many and test the conclusion with imputed SDs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(metafor)\nlibrary(ggplot2)\n\n# In the participant pack: data_file <- \"intercropping_biodiversity.csv\"\nic <- read.csv(data_file)\n\ngrp <- \"Pests\"        # <- in section 6 you will change this word only\n\nsub <- ic |>\n  filter(functional_group == grp, !sd_missing, !zero_mean)\n\ndat <- escalc(measure = \"ROM\",\n              m1i = b_mean_t, sd1i = b_sd_t, n1i = b_n_t,\n              m2i = b_mean_c, sd2i = b_sd_c, n2i = b_n_c,\n              data = sub)\n\nc(comparisons = nrow(dat), studies = n_distinct(dat$study_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomparisons     studies \n        382          28 \n```\n\n\n:::\n:::\n\n\nA small helper to turn lnRR into a % change:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npct <- function(x) round(100 * (exp(x) - 1), 1)\n```\n:::\n\n\n# Common vs random effects {#models}\n\n**Exercise 1.** Fit a common-effect model (`method = \"EE\"`) and a random-effects model (default estimator REML). `test = \"knha\"` (Knapp–Hartung) widens the CI slightly to account for the uncertainty in τ² — recommended. Compare the estimates and CIs in %.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ee <- rma(yi, vi, data = dat, method = \"___\")\nm_re <- rma(yi, vi, data = dat, test = \"knha\")\n\npct(c(m_ee$b, m_ee$ci.lb, m_ee$ci.ub))\npct(c(m_re$b, ___, ___))\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ee <- rma(yi, vi, data = dat, method = \"EE\")\nm_re <- rma(yi, vi, data = dat, test = \"knha\")\n\npct(c(m_ee$b, m_ee$ci.lb, m_ee$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -17.2 -17.3 -17.0\n```\n\n\n:::\n\n```{.r .cell-code}\npct(c(m_re$b, m_re$ci.lb, m_re$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -27.7 -32.7 -22.3\n```\n\n\n:::\n:::\n\n:::\n\n**Exercise 2.** Which study dominates? Compute the share of the total weight taken by each study in both models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_ee <- 1 / dat$vi\nw_re <- 1 / (dat$vi + m_re$___)\n\nshare <- function(w) sort(round(100 * tapply(w, dat$study_id, sum) / sum(w), 1), decreasing = TRUE)\nhead(share(w_ee), 3)\nhead(share(w_re), 3)\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nw_ee <- 1 / dat$vi\nw_re <- 1 / (dat$vi + m_re$tau2)\n\nshare <- function(w) sort(round(100 * tapply(w, dat$study_id, sum) / sum(w), 1), decreasing = TRUE)\nhead(share(w_ee), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 525  645  520 \n76.0 22.8  0.5 \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(share(w_re), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 645  525  740 \n26.2 16.9  6.5 \n```\n\n\n:::\n:::\n\n\nIn the common-effect model, **two studies carry almost all the weight** (study 525, Zhou et al. 2013, and study 645, Maluleke et al. 2005). In the random-effects model the weights are more equal — but study 645, which has 80 comparisons, now counts for about a quarter of the result **because it has many rows**. That is the non-independence problem of section 4.\n\nLook at `dat[dat$study_id == 525, c(\"b_mean_t\", \"b_mean_c\", \"b_n_t\", \"vi\")]`: n = 100 subsamples and the **same treatment means reused** against several controls give tiny variances. Always inspect your smallest variances — they may reveal pseudo-replication at extraction.\n:::\n\n# Heterogeneity and prediction interval {#hetero}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_re\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRandom-Effects Model (k = 382; tau^2 estimator: REML)\n\ntau^2 (estimated amount of total heterogeneity): 0.3386 (SE = 0.0296)\ntau (square root of estimated tau^2 value):      0.5819\nI^2 (total heterogeneity / total variability):   99.92%\nH^2 (total variability / sampling variability):  1227.22\n\nTest for Heterogeneity:\nQ(df = 381) = 159242.4776, p-val < .0001\n\nModel Results:\n\nestimate      se     tval   df    pval    ci.lb    ci.ub      \n -0.3244  0.0364  -8.9153  381  <.0001  -0.3960  -0.2529  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-caution icon=\"false\"}\n## Read the output (2 min)\nFind **τ²**, **I²** and **Q** in the output above. What does I² = 99.9% mean — and not mean?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Answer\"}\nτ² ≈ 0.34 (τ ≈ 0.58 on the lnRR scale): true effects vary a lot between comparisons. I² ≈ 99.9% means that almost all the observed variance is real heterogeneity rather than sampling error — because sampling errors are small here, not necessarily because effects are extremely different. I² is **relative**; τ and the prediction interval tell you **how much** effects vary.\n:::\n\n**Exercise 3.** Use `predict()` to get the mean, its CI **and the prediction interval**, back-transformed to %.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npr <- predict(m_re)\npct(c(mean = pr$pred, ci.lb = pr$ci.lb, ci.ub = pr$ci.ub, pi.lb = pr$___, pi.ub = pr$___))\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npr <- predict(m_re)\npct(c(mean = pr$pred, ci.lb = pr$ci.lb, ci.ub = pr$ci.ub, pi.lb = pr$pi.lb, pi.ub = pr$pi.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mean ci.lb ci.ub pi.lb pi.ub \n-27.7 -32.7 -22.3 -77.0 127.5 \n```\n\n\n:::\n:::\n\n\nIn a *typical* field, pests decrease with intercropping, and the CI excludes 0. But the prediction interval spans from a strong decrease to a strong **increase**: in a new field, the effect could go either way. (exp(mean) − 1 is the change in a typical — median — field; the average % change, exp(μ + τ²/2) − 1, is smaller here.)\n:::\n\n# Multilevel model and robust inference {#multilevel}\n\n**Exercise 4.** Fit a three-level model: comparisons (`es_id`) nested in studies (`study_id`). Use `test = \"t\", dfs = \"contain\"` so that the degrees of freedom follow the number of studies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ml <- rma.mv(yi, vi, random = ~ 1 | ___ / ___, data = dat, test = \"t\", dfs = \"contain\")\nm_ml\npct(c(m_ml$b, m_ml$ci.lb, m_ml$ci.ub))\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ml <- rma.mv(yi, vi, random = ~ 1 | study_id / es_id, data = dat, test = \"t\", dfs = \"contain\")\nm_ml\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 382; method: REML)\n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed          factor \nsigma^2.1  0.2055  0.4533     28     no        study_id \nsigma^2.2  0.1909  0.4369    382     no  study_id/es_id \n\nTest for Heterogeneity:\nQ(df = 381) = 159242.4776, p-val < .0001\n\nModel Results:\n\nestimate      se     tval  df    pval    ci.lb    ci.ub     \n -0.3138  0.0954  -3.2875  27  0.0028  -0.5096  -0.1179  ** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\npct(c(m_ml$b, m_ml$ci.lb, m_ml$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -26.9 -39.9 -11.1\n```\n\n\n:::\n:::\n\n\nThe two variance components are `sigma^2.1` (between studies) and `sigma^2.2` (between comparisons within studies). The mean is similar to the random-effects model, but the **CI is more than twice as wide**: we now have 28 studies, not 382 independent observations.\n:::\n\n*(optional)* How is the total variance split between the two levels? Multilevel I² [@nakagawa2012]: each variance component divided by the total, where the total also includes a \"typical\" sampling variance ṽ (a weighted average of the `vi`):\n\n$$I^2_{study} = \\frac{\\sigma^2_{study}}{\\sigma^2_{study} + \\sigma^2_{within} + \\tilde v}, \\qquad \\tilde v = \\frac{(k-1)\\sum w_i}{(\\sum w_i)^2 - \\sum w_i^2}, \\; w_i = 1/v_i$$\n\nCode given — just run it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw  <- 1 / dat$vi\nk  <- length(w)\nvt <- (k - 1) * sum(w) / (sum(w)^2 - sum(w^2))        # \"typical\" sampling variance\nround(100 * m_ml$sigma2 / (sum(m_ml$sigma2) + vt), 1)  # % between studies, % within studies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 51.8 48.1\n```\n\n\n:::\n:::\n\n\n**Exercise 5.** Add cluster-robust inference (a safety net if the dependence structure is misspecified).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_rob <- robust(m_ml, cluster = ___, clubSandwich = TRUE)\nm_rob\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nm_rob <- robust(m_ml, cluster = study_id, clubSandwich = TRUE)\nm_rob\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 382; method: REML)\n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed          factor \nsigma^2.1  0.2055  0.4533     28     no        study_id \nsigma^2.2  0.1909  0.4369    382     no  study_id/es_id \n\nTest for Heterogeneity:\nQ(df = 381) = 159242.4776, p-val < .0001\n\nNumber of estimates:   382\nNumber of clusters:    28\nEstimates per cluster: 1-80 (mean: 13.64, median: 8)\n\nModel Results:\n\nestimate      se¹     tval¹     df¹    pval¹    ci.lb¹    ci.ub¹     \n -0.3138  0.0951   -3.2990   26.09   0.0028   -0.5092   -0.1183   ** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n1) results based on cluster-robust inference (var-cov estimator: CR2,\n   approx t-test and confidence interval, df: Satterthwaite approx)\n```\n\n\n:::\n\n```{.r .cell-code}\npct(c(m_rob$b, m_rob$ci.lb, m_rob$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -26.9 -39.9 -11.2\n```\n\n\n:::\n:::\n\n\nClose to the multilevel result: good news, the model-based CI was not over-optimistic.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"(optional) Correlated sampling errors: shared control plots\"}\nWhen several treatments are compared with the same control, their sampling errors are correlated. A pragmatic \"working model\" (called CHE + RVE, @pustejovsky2022): assume a correlation (e.g. ρ = 0.5) between all rows of a study, build the variance–covariance matrix with `vcalc()`, and keep `robust()` on top. RVE needs enough studies (≳ 10–20 clusters; `clubSandwich = TRUE` adds the small-sample correction). The ρ assumption is strong; with good group identifiers, `vcalc()` can instead compute the covariance of shared controls exactly (arguments `grp1`, `grp2`, `w1`, `w2`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV <- vcalc(vi, cluster = study_id, obs = es_id, rho = 0.5, data = dat)\nm_v <- rma.mv(yi, V, random = ~ 1 | study_id / es_id, data = dat, test = \"t\", dfs = \"contain\")\npct(c(m_v$b, m_v$ci.lb, m_v$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -29.6 -42.1 -14.5\n```\n\n\n:::\n\n```{.r .cell-code}\nm_vr <- robust(m_v, cluster = study_id, clubSandwich = TRUE)\npct(c(m_vr$b, m_vr$ci.lb, m_vr$ci.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -29.6 -42.0 -14.5\n```\n\n\n:::\n:::\n\n\nTry ρ = 0.2 and 0.8: if the conclusion does not change, it is robust to this assumption.\n:::\n\n# Show the result: an orchard plot {#plot}\n\n**Exercise 6.** The plotting code is given: run it and **match each element to the output of `predict()`** (`pred`, `ci.lb`/`ci.ub`, `pi.lb`/`pi.ub`). Then answer: what share of the individual comparisons falls outside the prediction interval? Is that what you expected?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npr_ml <- predict(m_ml)\nset.seed(1)\nggplot(dat, aes(x = yi, y = 1)) +\n  geom_jitter(aes(size = 1 / sqrt(vi)), height = 0.3, alpha = 0.3, colour = \"#56B8B9\") +\n  annotate(\"segment\", x = pr_ml$pi.lb, xend = pr_ml$pi.ub, y = 1, yend = 1, linewidth = 1) +\n  annotate(\"segment\", x = pr_ml$ci.lb, xend = pr_ml$ci.ub, y = 1, yend = 1, linewidth = 4) +\n  annotate(\"point\", x = pr_ml$pred, y = 1, size = 6, shape = 21, fill = \"#BCCF00\") +\n  geom_vline(xintercept = 0, linetype = 2) +\n  scale_size_continuous(range = c(0.5, 5), guide = \"none\") +\n  scale_x_continuous(sec.axis = sec_axis(~ 100 * (exp(.) - 1), name = \"% change\",\n                                         breaks = c(-95, -75, -50, 0, 100, 300))) +\n  coord_cartesian(xlim = c(-4, 2)) +\n  labs(x = \"lnRR (pest abundance)\", y = NULL,\n       subtitle = paste0(\"k = \", nrow(dat), \" comparisons, \", n_distinct(dat$study_id), \" studies\")) +\n  theme_minimal(base_size = 13) +\n  theme(axis.text.y = element_blank(), panel.grid.major.y = element_blank())\n```\n\n::: {.cell-output-display}\n![](td_files/figure-html/ex6-solution-1.png){width=1350}\n:::\n:::\n\n\nThe `orchaRd` package [@nakagawa2021] draws these plots directly (`orchard_plot()`), including for moderators; it is installed from GitHub, so we build it by hand here.\n\n::: {.callout-note collapse=\"true\" title=\"Answer\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(dat$yi < pr_ml$pi.lb | dat$yi > pr_ml$pi.ub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1151832\n```\n\n\n:::\n:::\n\nAbout 12% here — more than the naive 5%. The prediction interval is for **true** effects; observed values add their own sampling error on top, and a few studies are extreme. Worth a look: which studies are they?\n:::\n\n# Your turn: natural enemies {#turn}\n\n**Predict first**: will intercropping increase or decrease natural enemies?\n\nThen go back to section 1, replace `grp <- \"Pests\"` by `grp <- \"Natural enemies\"`, and **rerun the script from the top**. Compare the multilevel estimate and prediction interval with those for pests.\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nne <- ic |>\n  filter(functional_group == \"Natural enemies\", !sd_missing, !zero_mean) |>\n  escalc(measure = \"ROM\", m1i = b_mean_t, sd1i = b_sd_t, n1i = b_n_t,\n         m2i = b_mean_c, sd2i = b_sd_c, n2i = b_n_c, data = _)\nm_ne <- rma.mv(yi, vi, random = ~ 1 | study_id / es_id, data = ne, test = \"t\", dfs = \"contain\")   # same as rerunning with grp <- \"Natural enemies\"\npr_ne <- predict(m_ne)\nc(k = nrow(ne), studies = n_distinct(ne$study_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      k studies \n    195      20 \n```\n\n\n:::\n\n```{.r .cell-code}\npct(c(mean = pr_ne$pred, ci.lb = pr_ne$ci.lb, ci.ub = pr_ne$ci.ub, pi.lb = pr_ne$pi.lb, pi.ub = pr_ne$pi.ub))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mean ci.lb ci.ub pi.lb pi.ub \n  8.3  -9.1  29.0 -57.0 172.8 \n```\n\n\n:::\n:::\n\n\nNatural enemies tend to be **more abundant** with intercropping, but the CI includes zero: the evidence is weaker than for pests. Comparing both groups properly requires a **meta-regression** (moderator = functional group): that is for the *Advanced methods* session.\n:::\n\n# Debrief and key messages {#key}\n\n::: {.callout-tip appearance=\"simple\" icon=\"false\"}\n1.  Weights follow precision; τ² tames very precise studies, the multilevel model stops studies with many rows from dominating.\n2.  Choose the model **a priori**: random effects, **multilevel** when studies give several effect sizes.\n3.  Report the mean **with** its CI, τ² and the **prediction interval**; add `robust()` as a safety net.\n4.  Show all the data: orchard plots.\n\n**Next session (15:00):** are these 28 studies a representative sample — or is there publication bias?\n:::\n\n## Going further in the online notebook {.unnumbered}\n\n-   [Dependence: map it before you model it](https://literaturesynthesis.github.io/notebook/chapters/dependence.html)\n-   [Combining effect sizes: fixed, random and multilevel models](https://literaturesynthesis.github.io/notebook/chapters/combining-effect-sizes.html)\n-   [One question from start to finish](https://literaturesynthesis.github.io/notebook/chapters/worked-example.html)\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "td_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}